version: '3.8'

services:
  backend-dev:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: abhishek1727/myshagun-backend:dev
    container_name: myshagun-backend-dev
    restart: unless-stopped
    ports:
      - "5002:5001"
    environment:
      - NODE_ENV=development
      - PORT=5001
    env_file:
      - ./backend/.env
    networks:
      - myshagun-network
    volumes:
      - ./backend:/app

  web-dev:
    build:
      context: ./web
      dockerfile: Dockerfile.dev
    image: abhishek1727/myshagun-web:dev
    container_name: myshagun-web-dev
    restart: unless-stopped
    ports:
      - "8082:8080"
    environment:
      - VITE_PROXY_TARGET=http://myshagun-backend-dev:5001
    networks:
      - myshagun-network
    volumes:
      - ./web:/app
      - /app/node_modules

networks:
  myshagun-network:
    driver: bridge
